### ISSUE TITLE
Support for external chaincode builders

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/microfab#30]
Add support to be able to run external builders. 
This is following the model of https://github.com/hyperledgendary/fabric-builders/blob/master/builders/external/README.md

To run in this manner:

Start microfab as normal, but ensure that it is attached to a known docker network
Create a `connection.json` file and package in a tgz as per normal chaincodes (see the notes above)
Install the tgz

Start the docker container with the chaincode as per the connection.json (on the same network)
Approve and Commit the chaincode as normal.

**Comment by sstone1** [comment]
Think this is done 👍
