### ISSUE TITLE
CouchDB Index Deployment

### ISSUE THREAD

**Issue by bonnieishiguro** [IBM-Blockchain/microfab#86]
Hello,

I am having trouble deploying CouchDB indexes alongside chaincode with microfab version 0.0.11. Is this something I should be able to do with this verison? Do you see anything missing in my setup or approach? Thank you for taking a look.

### Investigation with IBP VSCode extension

I originally ran into this when using the IBP VSCode extension to deploy a local Fabric 2 network, with a chaincode tar.gz that includes a CouchDB index .json file.

My setup:
- VSCode 1.55.0
- IBP extension 2.0.2
- go 1.14
- Index .json file in the /META-INF/statedb/couchdb/indexes directory
- Packaged the chaincode with `peer lifecycle chaincode package`
- Deployed to a local Fabric 2 network

**My chaincode with VSCode local Fabric network**

I saw no `Created CouchDB index` log in the docker container and a log like the following when executing my query transaction:

```
[    org1peer] 2021-04-14 22:20:18.056 UTC [couchdb] queryDocuments -> WARN 148 The query <QUERY STRING> caused the following warning: [_design/<INDEX DDOC>, <INDEX NAME> was not used because it is not a valid index for this query.
[    org1peer] No matching index found, create an index to optimize query time.]
```

**Tutorial chaincode with tutorial deploy script**

To determine whether the issue was with either how I created my index or packaged my chaincode,  I tried the [Fabric 2.2 CouchDB tutorial](https://hyperledger-fabric.readthedocs.io/en/release-2.2/couchdb_tutorial.html).  After running the [fabric-samples test-network](https://github.com/hyperledger/fabric-samples/tree/v2.2.2/test-network) deployCC.sh script, I saw the expected index creation log in the container:

```
[couchdb] createIndex -> INFO 072 Created CouchDB index [indexOwner] in state database [mychannel_ledger] using design document [_design/indexOwnerDoc]
```

**Tutorial chaincode with VSCode local Fabric network**:

Then tried deploying the same .tar.gz (packaged during the tutorial) on the VSCode local Fabric network and saw no `Created CouchDB index` log and the same `not a valid index` log that I saw with my chaincode during a query.

### Investigation with Microfab

**Tutorial chaincode with microfab network**:

Since the VSCode extension creates a microfab network, I tried separately standing one up using [these](https://fabcar-samples.github.io/docs/networks/microfab/) instructions. Deployed the tar.gz file from the HL tutorial.  No `Created CouchDB index` log in the microfab container and the below logs when executing my query transaction.

```
[   sampleorgpeer] 2021-04-15 21:52:30.149 UTC [couchdb] createDatabaseIfNotExist -> INFO 0b0 Created state database mychannel_ledger
[   sampleorgpeer] 2021-04-15 21:52:30.364 UTC [couchdb] queryDocuments -> WARN 0b1 The query [{"limit":1000,"selector":{"docType":"asset","owner":"tom"},"use_index":["_design/indexOwnerDoc","indexOwner"]}] caused the following warning: [_design/indexOwnerDoc, indexOwner was not used because it is not a valid index for this query.
[   sampleorgpeer] No matching index found, create an index to optimize query time.]
```

**Comment by bonnieishiguro** [comment]
Index JSON from the tutorial: `{"index":{"fields":["docType","owner"]},"ddoc":"indexOwnerDoc", "name":"indexOwner","type":"json"}`

**Comment by mbwhite** [comment]
I've done some investigating; I hit similar issues and discovered that one of the main Fabric JavaScript chaincode samples has the META-INF in the wrong directory.

Moving this to the correct location (at the root of the package) Microfab was working correctly. This has the same index `{"index":{"fields":["docType","owner"]},"ddoc":"indexOwnerDoc", "name":"indexOwner","type":"json"}`

If the root directory of my chaincode package is  /my-chaincode and I've got my-chaincode/package.json  the index needs to be for my-chaincode/META-INF/statedb/couchdb/indexes/myindexname.json

So I've seen both the test-network and microfab work correctly;  if after checking you're still seeing issues could you attach (or send separately) the `tar.gz` of the chaincode you're installing please ?  Thanks.
