### ISSUE TITLE
single Instance for CouchDB

### ISSUE THREAD

**Issue by alurujawahar** [IBM-Blockchain/microfab#88]
Hi,
I can see that only one couchdb instance is created for all the organisations. But, in traditional Hyperledger Fabric, there will be respective couchdb container for each organization. Is there any way where we can create multiple couchdb instances in MicroFab?

**Comment by davidkel** [comment]
Is there a problem with this ? The point of microfab is to have a very small running fabric network for development use, if you need something beyond that then I would suggest looking at things like test-network in fabric samples or minifab in hyperledger-labs

**Comment by alurujawahar** [comment]
Thank you so much @davidkel for suggesting me Minifab. That suits perfectly in my case.
